// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAArqCbiZVM-YVMsGkNBj5kKncogk2iNC0',
    appId: '1:749985319663:web:df595cfd9c295a77d7a91a',
    messagingSenderId: '749985319663',
    projectId: 'hackathon-494117',
    authDomain: 'hackathon-494117.firebaseapp.com',
    storageBucket: 'hackathon-494117.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpljyJKvdFw-JsZXVHgPTUdHxtK9X3jY',
    appId: '1:749985319663:android:4035fae903fd77e3d7a91a',
    messagingSenderId: '749985319663',
    projectId: 'hackathon-494117',
    storageBucket: 'hackathon-494117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASN_y-LL9IW2cmbFCRh29nWAHP2Q-xqW8',
    appId: '1:749985319663:ios:719be1b0a77604b8d7a91a',
    messagingSenderId: '749985319663',
    projectId: 'hackathon-494117',
    storageBucket: 'hackathon-494117.firebasestorage.app',
    iosBundleId: 'com.example.livreurInfflux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASN_y-LL9IW2cmbFCRh29nWAHP2Q-xqW8',
    appId: '1:749985319663:ios:719be1b0a77604b8d7a91a',
    messagingSenderId: '749985319663',
    projectId: 'hackathon-494117',
    storageBucket: 'hackathon-494117.firebasestorage.app',
    iosBundleId: 'com.example.livreurInfflux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAArqCbiZVM-YVMsGkNBj5kKncogk2iNC0',
    appId: '1:749985319663:web:6f7e791cdf918850d7a91a',
    messagingSenderId: '749985319663',
    projectId: 'hackathon-494117',
    authDomain: 'hackathon-494117.firebaseapp.com',
    storageBucket: 'hackathon-494117.firebasestorage.app',
  );
}
